### ISSUE TITLE
m_nocreate improvements

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd-contrib#235]
i think this improvement should be useful : 

- an option to don't affect registered users
- an option to don't affect registered channels
- when telluser="yes" is set send the reason instead of the default message "You are not allowed to create channels"

**Comment by genius3000** [comment]
>     * an option to don't affect registered users
I'll try to add something in a per X-line manner rather than a global config setting. I purposely left this kind of option out as the default supplied modules for oper-only or registered-only channel creation already cover this. 

>     * an option to don't affect registered channels
I don't think this is possible. Until a channel is created, the IRCd has no knowledge of it regardless of what services knows. Maybe there's some fun trickery that can be done, but I'd expect this to be a no-go. Ideas or obvious solutions that I'm missing are always appreciated.
 
>     * when telluser="yes" is set send the reason instead of the default message "You are not allowed to create channels"
This is easy enough; I'll probably add a configuration option for a default or to use the per X-line reason.

**Comment by genius3000** [comment]
This is taken care of with:
https://github.com/inspircd/inspircd-contrib/commit/e94c0b1b40a9ecc9234a7f54c1477f30475d7b33
* If `<nocreate:reason>` is not empty it will be used, otherwise the individual reason will be used. This only applies when `<nocreate:telluser>` is enabled.

https://github.com/inspircd/inspircd-contrib/commit/36ce6fce1ea5f12138fc348db7aefbebcedd0c56
*  Prefix a full `nick!user@host` mask with `U:` to match only unregistered users.

I'll regen the modules list after I update all the helpop examples in my modules.
